In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('/content/content  rating with string.csv')
X = dataset.iloc[:, :1].values


In [ ]:
print (X)

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
print(X)

  (0, 4)	1.0
  (1, 4)	1.0
  (2, 4)	1.0
  (3, 4)	1.0
  (4, 4)	1.0
  (5, 4)	1.0
  (6, 4)	1.0
  (7, 4)	1.0
  (8, 4)	1.0
  (9, 4)	1.0
  (10, 4)	1.0
  (11, 4)	1.0
  (12, 0)	1.0
  (13, 4)	1.0
  (14, 4)	1.0
  (15, 4)	1.0
  (16, 4)	1.0
  (17, 4)	1.0
  (18, 0)	1.0
  (19, 4)	1.0
  (20, 4)	1.0
  (21, 4)	1.0
  (22, 0)	1.0
  (23, 4)	1.0
  (24, 4)	1.0
  :	:
  (575, 1)	1.0
  (576, 1)	1.0
  (577, 2)	1.0
  (578, 1)	1.0
  (579, 1)	1.0
  (580, 1)	1.0
  (581, 2)	1.0
  (582, 2)	1.0
  (583, 1)	1.0
  (584, 1)	1.0
  (585, 1)	1.0
  (586, 1)	1.0
  (587, 1)	1.0
  (588, 2)	1.0
  (589, 2)	1.0
  (590, 2)	1.0
  (591, 1)	1.0
  (592, 2)	1.0
  (593, 1)	1.0
  (594, 1)	1.0
  (595, 4)	1.0
  (596, 1)	1.0
  (597, 2)	1.0
  (598, 4)	1.0
  (599, 1)	1.0


In [19]:
 pd.DataFrame(X.tolist(), columns=['content_rating'])

content_rating
0      (0, 4)\t1.0
1      (0, 4)\t1.0
2      (0, 4)\t1.0
3      (0, 4)\t1.0
4      (0, 4)\t1.0
..             ...
595    (0, 4)\t1.0
596    (0, 1)\t1.0
597    (0, 2)\t1.0
598    (0, 4)\t1.0
599    (0, 1)\t1.0

[600 rows x 1 columns]

In [20]:
 pd.DataFrame(X.tolist(), columns=['content_rating']).to_csv("Vectors for content_rating.csv")

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
similarity = cosine_similarity(X.tolist())

In [24]:
print(similarity)

[[1. 1. 1. ... 0. 1. 0.]
 [1. 1. 1. ... 0. 1. 0.]
 [1. 1. 1. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [1. 1. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [26]:
pd.DataFrame(similarity).to_csv("Similarity_content_rating.csv")