In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/genres (1).csv')

In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head()

genres
0                drama
1          crime drama
2        drama romance
3          drama scifi
4  crime drama romance

In [ ]:
# number of rows and columns in the data frame

movies_data.shape

(600, 1)

In [ ]:
selected_features = ['genres']
print(selected_features)

['genres']


In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
combined_features = movies_data['genres']

In [ ]:
print(combined_features)

0                            drama
1                      crime drama
2                    drama romance
3                      drama scifi
4              crime drama romance
                  ...             
595           comedy romance short
596           comedy drama romance
597                         horror
598    action crime drama thriller
599             action drama scifi
Name: genres, Length: 600, dtype: object


In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 4)	1.0
  (1, 3)	0.8673177466714759
  (1, 4)	0.49775488577081145
  (2, 7)	0.8269421690675243
  (2, 4)	0.562286981014053
  (3, 8)	0.8461519524690033
  (3, 4)	0.5329417166378457
  (4, 7)	0.5906828950282877
  (4, 3)	0.6998419721965319
  (4, 4)	0.4016403011066862
  (5, 7)	1.0
  (6, 4)	1.0
  (7, 7)	0.8269421690675243
  (7, 4)	0.562286981014053
  (8, 2)	0.6674501111944044
  (8, 7)	0.7446545165824062
  (9, 2)	0.5954690466255317
  (9, 7)	0.6643473536339999
  (9, 4)	0.45172913148299554
  (10, 2)	0.6674501111944044
  (10, 7)	0.7446545165824062
  (11, 2)	0.6674501111944044
  (11, 7)	0.7446545165824062
  (12, 2)	0.7966951409641522
  (12, 4)	0.6043813798952691
  :	:
  (589, 5)	0.7268044426797219
  (590, 7)	0.8269421690675243
  (590, 4)	0.562286981014053
  (591, 6)	0.6111536889623582
  (591, 2)	0.5056070760042316
  (591, 8)	0.6089767262893981
  (592, 6)	1.0
  (593, 1)	1.0
  (594, 1)	0.5562889839494299
  (594, 2)	0.5308244200371468
  (594, 8)	0.6393496707035498
  (595, 9)	0.888536787326286
  (59

Cosine Similarity

In [ ]:
pd.DataFrame(feature_vectors).to_csv("x_train_smote_oversample.csv")

In [ ]:
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.49775489 0.56228698 ... 0.         0.3535268  0.42830935]
 [0.49775489 1.         0.27988109 ... 0.         0.71024276 0.21319307]
 [0.56228698 0.27988109 1.         ... 0.         0.19878352 0.24083277]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.3535268  0.71024276 0.19878352 ... 0.         1.         0.44370499]
 [0.42830935 0.21319307 0.24083277 ... 0.         0.44370499 1.        ]]


In [ ]:
print(similarity.shape)

(600, 600)


In [ ]:
pd.DataFrame(similarity).to_csv("Similarity.csv")